-- Adminer 4.2.4 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP VIEW IF EXISTS `v1_pindahtangan`;
CREATE TABLE `v1_pindahtangan` (`id` int(9) unsigned, `id_bukuinduk` int(9) unsigned, `uraian` varchar(200), `ket_hapus` varchar(200), `tahun` char(4), `jml_barang` int(9), `jml_harga` decimal(18,2), `ket` varchar(200), `kondisi` char(1), `status_barang` char(1), `asal_usul` char(1), `satuan` varchar(15), `tgl_buku` date, `tgl_sensus` datetime, `a1` char(2), `a` char(2), `b` char(2), `c` char(2), `d` char(2), `e` char(2), `f` char(2), `g` char(2), `h` char(2), `i` char(2), `j` char(3), `thn_perolehan` char(4), `noreg` char(6), `nm_barang` varchar(100), `tgl_pemindahtanganan` date, `bentuk_pemindahtanganan` char(1), `kepada_nama` varchar(50), `kepada_alamat` varchar(50), `kondisi_akhir` char(1), `idbi_awal` int(11), `e1` char(3), `aset_tetap` int(1), `nosk` varchar(60), `tglsk` date, `staset` tinyint(3), `verifikasi` tinyint(3), `c1` char(1), `f1` char(1), `f2` char(1), `st_hapus` char(1), `nilai_susut` decimal(18,2), `nilai_buku` decimal(18,2));


DROP VIEW IF EXISTS `v_pemanfaat`;
CREATE TABLE `v_pemanfaat` (`id` int(9) unsigned, `id_bukuinduk` int(9) unsigned, `tgl_pemanfaatan` date, `tgl_pemanfaatan_akhir` date, `bentuk_pemanfaatan` char(1), `uraian` text, `kepada_instansi` varchar(50), `kepada_alamat` varchar(50), `kepada_nama` varchar(50), `kepada_jabatan` varchar(50), `surat_no` varchar(50), `surat_tgl` date, `jangkawaktu` int(4), `biaya_pemanfaatan` decimal(18,2), `ket` varchar(200), `tahun` char(4), `idbi_awal` int(11), `tgl_update` datetime, `uid` varchar(20), `a1` char(2), `a` char(2), `b` char(2), `c1` char(1), `c` char(2), `d` char(2), `e` char(2), `e1` char(3), `f` char(2), `g` char(2), `h` char(2), `i` char(2), `j` char(3), `thn_perolehan` char(4), `noreg` char(6), `nm_barang` varchar(100), `f1` char(1), `f2` char(1), `nilai_susut` decimal(18,2));


DROP VIEW IF EXISTS `v_pemusnahan`;
CREATE TABLE `v_pemusnahan` (`Id` int(11) unsigned, `id_bukuinduk` int(11) unsigned, `c1` char(1), `c` char(2), `d` char(2), `e` char(2), `e1` char(3), `f` char(2), `g` char(2), `h` char(2), `i` char(2), `j` char(3), `noreg` char(4), `thn_perolehan` char(4), `jumlah_harga` decimal(18,2), `refid_pemusnahan` int(11), `ket` varchar(200), `kondisi` char(1), `k` char(1), `l` char(1), `m` char(1), `n` char(2), `o` char(2), `p` char(2), `thn_akun` int(11), `no_ba` varchar(30), `tgl_ba` date, `sttemp` tinyint(3), `thn_anggaran` int(4), `f1` char(1), `f2` char(1), `cara_pemusnahan` varchar(200), `idbi_awal` int(11) unsigned, `tgl_buku` date, `st_hapus` char(1), `nilai_susut` decimal(18,2));


DROP TABLE IF EXISTS `v1_pindahtangan`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v1_pindahtangan` AS select `aa`.`id` AS `id`,`aa`.`id_bukuinduk` AS `id_bukuinduk`,`aa`.`uraian` AS `uraian`,`aa`.`ket` AS `ket_hapus`,`aa`.`tahun` AS `tahun`,`bb`.`jml_barang` AS `jml_barang`,`bb`.`jml_harga` AS `jml_harga`,`aa`.`ket` AS `ket`,`bb`.`kondisi` AS `kondisi`,`bb`.`status_barang` AS `status_barang`,`bb`.`asal_usul` AS `asal_usul`,`bb`.`satuan` AS `satuan`,`bb`.`tgl_buku` AS `tgl_buku`,`bb`.`tgl_sensus` AS `tgl_sensus`,`bb`.`a1` AS `a1`,`bb`.`a` AS `a`,`bb`.`b` AS `b`,`bb`.`c` AS `c`,`bb`.`d` AS `d`,`bb`.`e` AS `e`,`bb`.`f` AS `f`,`bb`.`g` AS `g`,`bb`.`h` AS `h`,`bb`.`i` AS `i`,`bb`.`j` AS `j`,`bb`.`thn_perolehan` AS `thn_perolehan`,`bb`.`noreg` AS `noreg`,`cc`.`nm_barang` AS `nm_barang`,`aa`.`tgl_pemindahtanganan` AS `tgl_pemindahtanganan`,`aa`.`bentuk_pemindahtanganan` AS `bentuk_pemindahtanganan`,`aa`.`kepada_nama` AS `kepada_nama`,`aa`.`kepada_alamat` AS `kepada_alamat`,`aa`.`kondisi_akhir` AS `kondisi_akhir`,`bb`.`idawal` AS `idbi_awal`,`bb`.`e1` AS `e1`,if(((`bb`.`f` = '02') or ((`bb`.`f` = '03') and (`bb`.`kondisi` = 3))),0,if((`bb`.`kondisi` <= 3),1,2)) AS `aset_tetap`,`aa`.`nosk` AS `nosk`,`aa`.`tglsk` AS `tglsk`,`bb`.`staset` AS `staset`,`bb`.`verifikasi` AS `verifikasi`,`bb`.`c1` AS `c1`,`bb`.`f1` AS `f1`,`bb`.`f2` AS `f2`,`aa`.`st_hapus` AS `st_hapus`,`aa`.`nilai_susut` AS `nilai_susut`,`aa`.`nilai_buku` AS `nilai_buku` from ((`pemindahtanganan` `aa` left join `buku_induk` `bb` on((`aa`.`id_bukuinduk` = `bb`.`id`))) left join `ref_barang` `cc` on(((`bb`.`f` = `cc`.`f`) and (`bb`.`g` = `cc`.`g`) and (`bb`.`h` = `cc`.`h`) and (`bb`.`i` = `cc`.`i`) and (`bb`.`j` = `cc`.`j`))));

DROP TABLE IF EXISTS `v_pemanfaat`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_pemanfaat` AS select `aa`.`id` AS `id`,`aa`.`id_bukuinduk` AS `id_bukuinduk`,`aa`.`tgl_pemanfaatan` AS `tgl_pemanfaatan`,`aa`.`tgl_pemanfaatan_akhir` AS `tgl_pemanfaatan_akhir`,`aa`.`bentuk_pemanfaatan` AS `bentuk_pemanfaatan`,`aa`.`uraian` AS `uraian`,`aa`.`kepada_instansi` AS `kepada_instansi`,`aa`.`kepada_alamat` AS `kepada_alamat`,`aa`.`kepada_nama` AS `kepada_nama`,`aa`.`kepada_jabatan` AS `kepada_jabatan`,`aa`.`surat_no` AS `surat_no`,`aa`.`surat_tgl` AS `surat_tgl`,`aa`.`jangkawaktu` AS `jangkawaktu`,`aa`.`biaya_pemanfaatan` AS `biaya_pemanfaatan`,`aa`.`ket` AS `ket`,`aa`.`tahun` AS `tahun`,`aa`.`idbi_awal` AS `idbi_awal`,`aa`.`tgl_update` AS `tgl_update`,`aa`.`uid` AS `uid`,`bb`.`a1` AS `a1`,`bb`.`a` AS `a`,`bb`.`b` AS `b`,`bb`.`c1` AS `c1`,`bb`.`c` AS `c`,`bb`.`d` AS `d`,`bb`.`e` AS `e`,`bb`.`e1` AS `e1`,`bb`.`f` AS `f`,`bb`.`g` AS `g`,`bb`.`h` AS `h`,`bb`.`i` AS `i`,`bb`.`j` AS `j`,`bb`.`thn_perolehan` AS `thn_perolehan`,`bb`.`noreg` AS `noreg`,`bb`.`nm_barang` AS `nm_barang`,`bb`.`f1` AS `f1`,`bb`.`f2` AS `f2`,`aa`.`nilai_susut` AS `nilai_susut` from (`pemanfaatan` `aa` left join `view_buku_induk2` `bb` on((`aa`.`id_bukuinduk` = `bb`.`id`)));

DROP TABLE IF EXISTS `v_pemusnahan`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_pemusnahan` AS select `aa`.`Id` AS `Id`,`aa`.`id_bukuinduk` AS `id_bukuinduk`,`aa`.`c1` AS `c1`,`aa`.`c` AS `c`,`aa`.`d` AS `d`,`aa`.`e` AS `e`,`aa`.`e1` AS `e1`,`aa`.`f` AS `f`,`aa`.`g` AS `g`,`aa`.`h` AS `h`,`aa`.`i` AS `i`,`aa`.`j` AS `j`,`aa`.`noreg` AS `noreg`,`aa`.`thn_perolehan` AS `thn_perolehan`,`aa`.`jumlah_harga` AS `jumlah_harga`,`aa`.`refid_pemusnahan` AS `refid_pemusnahan`,`aa`.`ket` AS `ket`,`aa`.`kondisi` AS `kondisi`,`aa`.`k` AS `k`,`aa`.`l` AS `l`,`aa`.`m` AS `m`,`aa`.`n` AS `n`,`aa`.`o` AS `o`,`aa`.`p` AS `p`,`aa`.`thn_akun` AS `thn_akun`,`bb`.`no_ba` AS `no_ba`,`bb`.`tgl_ba` AS `tgl_ba`,`bb`.`sttemp` AS `sttemp`,`bb`.`thn_anggaran` AS `thn_anggaran`,`aa`.`f1` AS `f1`,`aa`.`f2` AS `f2`,`bb`.`cara_pemusnahan` AS `cara_pemusnahan`,`aa`.`idbi_awal` AS `idbi_awal`,`aa`.`tgl_buku` AS `tgl_buku`,`aa`.`st_hapus` AS `st_hapus`,`aa`.`nilai_susut` AS `nilai_susut` from (`pemusnahan_det` `aa` left join `pemusnahan` `bb` on((`aa`.`refid_pemusnahan` = `bb`.`id`)));

-- 2018-02-28 06:31:37
